/**
 * `loopback-mcp-server init` — onboard the current repo onto the Loopback hub.
 *
 * Renders the ONE canonical queue playbook (integrations/instructions-src.md)
 * and the ONE canonical skill (skills/loopback/SKILL.md) into every agent's
 * NATIVE mechanism, treating Claude Code, Codex, and Gemini CLI as peers:
 *
 *   AGENTS.md                          canonical section (Codex + Gemini read natively)
 *   CLAUDE.md                          @AGENTS.md import (Claude Code)
 *   GEMINI.md                          @AGENTS.md import (Gemini CLI memport)
 *   .claude/skills/loopback/SKILL.md   Claude Code native skill
 *   .agents/skills/loopback/SKILL.md   Codex native skill
 *   .gemini/commands/loopback.toml     Gemini /loopback custom command
 *   .mcp.json                          Claude Code project MCP config
 *   .gemini/settings.json              Gemini MCP config + context.fileName
 *   .codex/config.toml                 Codex project-scoped MCP config
 *
 * Merges are non-destructive: existing files are appended to or key-merged,
 * never clobbered; marker comments make re-runs idempotent. Default is a dry
 * run — pass --write to apply.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, "..");
const REPO_SPEC = "github:joshidikshant/loopback";

const SECTION_BEGIN = "<!-- loopback:queue:begin -->";
const SECTION_END = "<!-- loopback:queue:end -->";
const GENERATED_MARK =
  "<!-- generated by `loopback-mcp-server init`; re-runs refresh it — remove this line to hand-maintain -->";

const AGENT_NAMES = ["claude", "codex", "gemini"] as const;
type AgentName = (typeof AGENT_NAMES)[number];

interface InitOptions {
  project: string;
  agents: AgentName[];
  write: boolean;
  cwd: string;
}

type ActionState = "create" | "update" | "unchanged" | "kept";

interface FileAction {
  path: string;
  state: ActionState;
  note?: string;
  content?: string;
}

const INIT_USAGE = `loopback-mcp-server init — onboard this repo onto the Loopback hub

Usage (run from inside a consuming repo):
  loopback-mcp-server init --project <slug>                 # dry run: show what would change
  loopback-mcp-server init --project <slug> --write         # apply
  loopback-mcp-server init --project <slug> --agents claude,codex   # subset (default: all three)

Writes/merges (non-destructively, idempotently):
  AGENTS.md (canonical queue section) · CLAUDE.md + GEMINI.md (@AGENTS.md imports)
  .claude/skills/loopback/SKILL.md + .agents/skills/loopback/SKILL.md (same skill, both natives)
  .mcp.json + .gemini/settings.json + .codex/config.toml (MCP registration ×3)
  .gemini/commands/loopback.toml (/loopback command)
`;

function fail(message: string): never {
  console.error(`init error: ${message}`);
  process.exit(1);
}

function parseArgs(argv: string[], cwd: string): InitOptions {
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(INIT_USAGE);
    process.exit(0);
  }
  const value = (flag: string): string | undefined => {
    const idx = argv.indexOf(flag);
    return idx !== -1 && idx + 1 < argv.length ? argv[idx + 1] : undefined;
  };
  const project = value("--project");
  if (!project) fail("--project <slug> is required. See: loopback-mcp-server init --help");
  if (!/^[a-z0-9][a-z0-9._-]*$/i.test(project)) {
    fail(`invalid project slug '${project}' — use letters, digits, ., _, -`);
  }
  const agentsRaw = value("--agents");
  let agents: AgentName[] = [...AGENT_NAMES];
  if (agentsRaw) {
    const parsed = agentsRaw.split(",").map((a) => a.trim().toLowerCase());
    const bad = parsed.filter((a) => !(AGENT_NAMES as readonly string[]).includes(a));
    if (bad.length) fail(`unknown agent(s) '${bad.join(", ")}' — valid: claude, codex, gemini`);
    agents = parsed as AgentName[];
  }
  return { project, agents, write: argv.includes("--write"), cwd };
}

/** Canonical sources ship inside the package; a missing one means a broken install. */
function loadCanonical(relPath: string): string {
  const abs = join(PACKAGE_ROOT, relPath);
  try {
    return readFileSync(abs, "utf-8");
  } catch {
    fail(`canonical source '${relPath}' not found at ${abs} — reinstall loopback-mcp-server`);
  }
}

function playbookSection(project: string): string {
  const src = loadCanonical("integrations/instructions-src.md");
  const match = src.match(/<!-- playbook:begin -->([\s\S]*?)<!-- playbook:end -->/);
  if (!match) fail("integrations/instructions-src.md is missing its playbook markers");
  return match[1].trim().replaceAll("{{PROJECT}}", project);
}

function renderedSkill(project: string): string {
  const src = loadCanonical("skills/loopback/SKILL.md");
  const lines = src.split("\n");
  const closing = lines.findIndex((line, i) => i > 0 && line.trim() === "---");
  if (lines[0]?.trim() !== "---" || closing === -1) {
    fail("skills/loopback/SKILL.md has no valid frontmatter");
  }
  lines.splice(
    closing + 1,
    0,
    "",
    GENERATED_MARK,
    "",
    `**Project slug for this repo: \`${project}\`.**`,
  );
  return lines.join("\n");
}

/**
 * How agent configs should launch the server.
 *
 * - Server lives inside the repo being onboarded (Loopback onboarding itself,
 *   or a monorepo vendoring it) → repo-relative path, so the committed config
 *   works on every clone and leaks no machine paths.
 * - Stable checkout elsewhere → absolute path (fast startup).
 * - Ephemeral npx run → `npx github:` (nothing stable to point at).
 */
function serverCommand(cwd: string): { command: string; args: string[] } {
  const entry = resolve(PACKAGE_ROOT, "dist", "index.js");
  const ephemeral = entry.split(sep).includes("_npx");
  if (ephemeral || !existsSync(entry)) return { command: "npx", args: ["-y", REPO_SPEC] };
  const inside = relative(cwd, entry);
  if (!inside.startsWith("..") && !isAbsolute(inside)) {
    return { command: "node", args: [`./${inside.split(sep).join("/")}`] };
  }
  return { command: "node", args: [entry] };
}

function readIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, "utf-8") : null;
}

// ---------- renderers (pure: existing content in, action out) ----------

export function renderAgentsMd(existing: string | null, section: string): FileAction {
  const block = `${SECTION_BEGIN}\n## Working the Loopback queue\n\n${section}\n${SECTION_END}`;
  if (existing === null) {
    return {
      path: "AGENTS.md",
      state: "create",
      content: `# Agent instructions\n\n${block}\n`,
    };
  }
  if (existing.includes(SECTION_BEGIN) && existing.includes(SECTION_END)) {
    const replaced = existing.replace(
      new RegExp(`${SECTION_BEGIN}[\\s\\S]*?${SECTION_END}`),
      block,
    );
    return replaced === existing
      ? { path: "AGENTS.md", state: "unchanged" }
      : { path: "AGENTS.md", state: "update", note: "refreshed queue section", content: replaced };
  }
  return {
    path: "AGENTS.md",
    state: "update",
    note: "appended queue section",
    content: `${existing.trimEnd()}\n\n${block}\n`,
  };
}

export function renderPointer(existing: string | null, fileName: string): FileAction {
  const hasImport = /@(\.\/)?AGENTS\.md/.test(existing ?? "");
  if (existing === null) {
    return {
      path: fileName,
      state: "create",
      content: `<!-- Cross-agent instructions live in AGENTS.md (canonical); imported below. -->\n\n@AGENTS.md\n`,
    };
  }
  if (hasImport) return { path: fileName, state: "unchanged" };
  return {
    path: fileName,
    state: "update",
    note: "appended @AGENTS.md import",
    content: `${existing.trimEnd()}\n\n@AGENTS.md\n`,
  };
}

export function renderSkillInstall(existing: string | null, skill: string, path: string): FileAction {
  if (existing === null) return { path, state: "create", content: skill };
  if (existing === skill) return { path, state: "unchanged" };
  if (!existing.includes(GENERATED_MARK)) {
    return { path, state: "kept", note: "hand-maintained (no generated marker) — left untouched" };
  }
  return { path, state: "update", note: "refreshed from canonical skill", content: skill };
}

export function renderMcpJson(
  existing: string | null,
  cmd: { command: string; args: string[] },
): FileAction {
  const path = ".mcp.json";
  let obj: Record<string, unknown> = {};
  if (existing !== null) {
    try {
      obj = JSON.parse(existing) as Record<string, unknown>;
    } catch {
      return { path, state: "kept", note: "existing file is not valid JSON — left untouched" };
    }
  }
  const servers = (obj.mcpServers ?? {}) as Record<string, unknown>;
  if ("loopback" in servers) {
    return { path, state: existing === null ? "create" : "kept", note: "loopback entry already present" };
  }
  servers.loopback = { command: cmd.command, args: cmd.args };
  obj.mcpServers = servers;
  return {
    path,
    state: existing === null ? "create" : "update",
    note: "added mcpServers.loopback",
    content: `${JSON.stringify(obj, null, 2)}\n`,
  };
}

export function renderGeminiSettings(
  existing: string | null,
  cmd: { command: string; args: string[] },
): FileAction {
  const path = ".gemini/settings.json";
  let obj: Record<string, unknown> = {};
  if (existing !== null) {
    try {
      obj = JSON.parse(existing) as Record<string, unknown>;
    } catch {
      return { path, state: "kept", note: "existing file is not valid JSON — left untouched" };
    }
  }
  let changed = false;

  // context.fileName must include AGENTS.md (and keep GEMINI.md working).
  const context = (obj.context ?? {}) as Record<string, unknown>;
  const current = context.fileName;
  let fileNames: string[];
  if (current === undefined) fileNames = [];
  else if (typeof current === "string") fileNames = [current];
  else if (Array.isArray(current)) fileNames = current.filter((f): f is string => typeof f === "string");
  else fileNames = [];
  if (fileNames.length === 0) fileNames = ["GEMINI.md"];
  for (const wanted of ["AGENTS.md", "GEMINI.md"]) {
    if (!fileNames.includes(wanted)) {
      fileNames.push(wanted);
      changed = true;
    }
  }
  if (changed || current === undefined) {
    context.fileName = fileNames;
    obj.context = context;
    changed = true;
  }

  const servers = (obj.mcpServers ?? {}) as Record<string, unknown>;
  if (!("loopback" in servers)) {
    servers.loopback = { command: cmd.command, args: cmd.args };
    obj.mcpServers = servers;
    changed = true;
  }

  if (!changed && existing !== null) return { path, state: "unchanged" };
  return {
    path,
    state: existing === null ? "create" : "update",
    note: "context.fileName + mcpServers.loopback",
    content: `${JSON.stringify(obj, null, 2)}\n`,
  };
}

export function codexToml(cmd: { command: string; args: string[] }): string {
  const args = cmd.args.map((a) => JSON.stringify(a)).join(", ");
  return `# Loopback feedback bus (written by \`loopback-mcp-server init\`)
[mcp_servers.loopback]
command = ${JSON.stringify(cmd.command)}
args = [${args}]
`;
}

export function renderCodexConfig(
  existing: string | null,
  cmd: { command: string; args: string[] },
): FileAction {
  const path = ".codex/config.toml";
  if (existing === null) return { path, state: "create", content: codexToml(cmd) };
  if (existing.includes("[mcp_servers.loopback]")) {
    return { path, state: "unchanged", note: "loopback entry already present" };
  }
  return {
    path,
    state: "update",
    note: "appended mcp_servers.loopback",
    content: `${existing.trimEnd()}\n\n${codexToml(cmd)}`,
  };
}

export function renderGeminiCommand(existing: string | null, project: string): FileAction {
  const path = ".gemini/commands/loopback.toml";
  if (existing !== null) return { path, state: "unchanged", note: "existing command kept" };
  const content = `# ${GENERATED_MARK}
description = "Work the Loopback feedback queue for this repo (project: ${project})"
prompt = """
Work the Loopback feedback queue for project \`${project}\`, following the
'Working the Loopback queue' section of AGENTS.md: list open items, claim as
'gemini', read all captured context (extra.failed_responses, console,
extra.context run metadata), comment the root cause, fix, link the change,
mark fixed, verify for real, then resolve verified.

{{args}}
"""
`;
  return { path, state: "create", content };
}

// ---------- driver ----------

function widgetEmbed(project: string): string {
  return `<script src="http://127.0.0.1:7077/widget.js"
        data-project="${project}"
        data-endpoint="http://127.0.0.1:7077"></script>`;
}

export async function runInit(argv: string[]): Promise<void> {
  const opts = parseArgs(argv, process.cwd());
  const cmd = serverCommand(opts.cwd);
  const section = playbookSection(opts.project);
  const skill = renderedSkill(opts.project);
  const has = (agent: AgentName): boolean => opts.agents.includes(agent);

  const actions: FileAction[] = [];
  const at = (rel: string): string => join(opts.cwd, rel);

  // AGENTS.md is canonical and always rendered, whatever the agent subset.
  actions.push(renderAgentsMd(readIfExists(at("AGENTS.md")), section));
  if (has("claude")) {
    actions.push(renderPointer(readIfExists(at("CLAUDE.md")), "CLAUDE.md"));
    actions.push(
      renderSkillInstall(readIfExists(at(".claude/skills/loopback/SKILL.md")), skill, ".claude/skills/loopback/SKILL.md"),
    );
    actions.push(renderMcpJson(readIfExists(at(".mcp.json")), cmd));
  }
  if (has("codex")) {
    actions.push(
      renderSkillInstall(readIfExists(at(".agents/skills/loopback/SKILL.md")), skill, ".agents/skills/loopback/SKILL.md"),
    );
    actions.push(renderCodexConfig(readIfExists(at(".codex/config.toml")), cmd));
  }
  if (has("gemini")) {
    actions.push(renderPointer(readIfExists(at("GEMINI.md")), "GEMINI.md"));
    actions.push(renderGeminiSettings(readIfExists(at(".gemini/settings.json")), cmd));
    actions.push(renderGeminiCommand(readIfExists(at(".gemini/commands/loopback.toml")), opts.project));
  }

  const mode = opts.write ? "write" : "dry-run (pass --write to apply)";
  console.log(`\nLoopback init — project '${opts.project}' · agents: ${opts.agents.join(", ")} · ${mode}\n`);

  for (const action of actions) {
    if (opts.write && action.content !== undefined && (action.state === "create" || action.state === "update")) {
      mkdirSync(dirname(at(action.path)), { recursive: true });
      writeFileSync(at(action.path), action.content);
    }
    const verb = { create: "create", update: "merge ", unchanged: "ok    ", kept: "kept  " }[action.state];
    console.log(`  ${opts.write ? verb : `would ${verb.trim()}`}  ${action.path}${action.note ? `  (${action.note})` : ""}`);
  }

  console.log(`\n── AGENTS.md queue section (canonical rendering) ──\n`);
  console.log(section);
  console.log(`\n── Widget embed (paste into your app's HTML, before </body>) ──\n`);
  console.log(widgetEmbed(opts.project));
  console.log(`\n── Codex global alternative (~/.codex/config.toml), if you prefer machine scope ──\n`);
  console.log(codexToml(cmd).trimEnd());
  console.log(`
── Next ──
  1. Keep one central instance alive:  loopback-mcp-server --http   (see integrations/keep-alive.md)
  2. Paste the widget tag above into the app you want feedback on.
  3. In any agent here, say: "work the feedback queue for ${opts.project}".
     Codex project config loads when you trust this repo in Codex.
`);
}
